drop table users if exists;

create table users (
    id bigint generated by default as identity primary key,
    login varchar(80) not null,
    password varchar(80) not null,
    bitwiseRole integer default 0 not null,
    UNIQUE (login)
);

